### ISSUE TITLE
Dimensions

### ISSUE THREAD

**Issue by MatthewJA** [MatthewJA/Graphical-Equation-Manipulator#12]
Variables need dimensions.

**Comment by MatthewJA** [comment]
I'm kinda unsure how this should work.

See also MatthewJA/Coffeequate#31.

**Comment by bshlgrs** [comment]
## Backend:

The easiest way is we just annotate every variable in the database with its dimension, then check that they're equal when the user tries to equate them. We can demand the user provide dimensions for everything when they create their own equations, or when they add numerical values. I am totally okay with this route.

The only time that would be arduous would be when the user is entering in their own equations. Maybe we could make some kind of pretty interface for that?

For bonus points, we could have the system infer units and only complain when the user had done something ridiculous. This would be much harder and is not worth the effort.

## Frontend:

Here's my current vision:
- All numerical values entered must have dimensions.
- Dimensions appear whenever you've calculated a complete numerical value.

**Comment by MatthewJA** [comment]
I'm going to start with an extremely basic method of handling units. If you specify units at all, you have to specify all units. If you don't specify, then it's left unitless. I'll stop people from equating things which are not the same units.

**Comment by MatthewJA** [comment]
variables can now have units. To do: probably more validation stuff
