### ISSUE TITLE
Equations could appear in a prettier position

### ISSUE THREAD

**Issue by bshlgrs** [MatthewJA/Graphical-Equation-Manipulator#32]
It would be great if equations stacked vertically as you created them, with a bit more padding between each other than you're currently giving them. And the first one should start a bit farther from the top left.

**Comment by bshlgrs** [comment]
Example:

![untitled](https://f.cloud.github.com/assets/2689010/1885104/a23f9ede-79bf-11e3-89e6-907aafab2c89.jpg)

**Comment by MatthewJA** [comment]
Would dumping the equation in a random spot be a decent fix for now?
