### ISSUE TITLE
Enable deleting things

### ISSUE THREAD

**Issue by bshlgrs** [MatthewJA/Graphical-Equation-Manipulator#42]
We could have a garbage bin icon which you drag things to to delete them. Alternatively, we could destroy on right click. Or both.

**Comment by MatthewJA** [comment]
We can currently right click on things to delete them, it's just a bit buggy.

**Comment by MatthewJA** [comment]
Does the existing system not work?

**Comment by bshlgrs** [comment]
ah, I was unaware of that _shrinks away_

Maybe a garbage bin would be more intuitive? The way it currently works is probably fine though.

**Comment by MatthewJA** [comment]
Would you drag the equation so it partially covers the bin, or so that the pointer goes over the bin?

**Comment by bshlgrs** [comment]
Whichever one seems more intuitive/easier to implement to you.

**Comment by MatthewJA** [comment]
Thing is, the pointer one won't work because of boundaries and the other
might glitch badly. I think right clicking is safer.
